### ISSUE TITLE
Change app description to be more focused for our purpose

### ISSUE THREAD

**Issue by gteti** [aquariophilie/axolotl#28]
```yml
modules:
  macro:
    - key: qr-code
      function: main
      title: Axolotl QR Code
      description: Displays a QR Code 
      config:
        function: config
  function:
    - key: main
      handler: index.run
    - key: config
      handler: index.config
app:
  id: ari:cloud:ecosystem::app/f4f9a8eb-0012-4591-9425-7d6d8d48ff36
permissions:
  scopes:
    - 'read:confluence-content.summary'
```

I think that the description should be change to something like:
`description: Displays a QR Code connect to a capping machine report.`

I wanted some feedback before making a PR.
@gmacario @Raffone17 @GGn0
